version: "3.8"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - "./api/schema/mysql.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./api/data/users.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./api/data/posts.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./api/data/comments.sql:/docker-entrypoint-initdb.d/4.sql"
      - "./api/data/relationships.sql:/docker-entrypoint-initdb.d/5.sql"
      - "./api/data/likes.sql:/docker-entrypoint-initdb.d/6.sql"
      - "./api/data/stories.sql:/docker-entrypoint-initdb.d/7.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app/
      - /app/node_modules
    ports:
      - 3000:3000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app/
      - /app/node_modules
    ports:
      - 8800:8800
    environment:
      - DB_DEPLOYMENT_TYPE=docker
      - DB_TYPE=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_PASSWORD=example
      - DB_NAME=social
      - DB_USER=root
