version: "3.8"

services:
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app/
      - /app/node_modules
    ports:
      - 3000:3000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app/
      - /app/node_modules
    ports:
      - 8800:8800
    environment:
      - DB_TYPE=mysql
      - DB_HOST=[MYSQL_REMOTE_HOST]
      - DB_PORT=3306
      - DB_PASSWORD=[MYSQL_REMOTE_PASSWORD]
      - DB_NAME=social
      - DB_USER=root
