version: "3.8"

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app/
      - /app/node_modules #TODO: find out why I need this for npm packages to be available
    ports:
      - 3000:3000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app/
      - /app/node_modules #TODO: find out why I need this for npm packages to be available
    ports:
      - 8800:8800
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db # internal Docker connection
      - DB_PASSWORD=example
      - DB_NAME=social
      - DB_USER=root
